spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/aad_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
