services:
  aad_db2:
    image: postgres:15
    container_name: aad_database
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: aad_database   # <-- CREA LA BASE DE DATOS
    volumes:
      - ./data2:/var/lib/postgresql/data
