services:
  db:
    image: postgres:latest
    container_name: aad_db_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: aad_db
    ports:
      - "5433:5432"
    volumes:
      - resources_db_data:/var/lib/postgresql/data

volumes:
  resources_db_data:
  #a
##a