DROP TABLE IF EXISTS matricula CASCADE;
DROP TABLE IF EXISTS modulo CASCADE;
DROP TABLE IF EXISTS alumno CASCADE;

CREATE TABLE alumno (
    id SERIAL PRIMARY KEY,
    nif VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
);

CREATE TABLE modulo (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    horas INT NOT NULL
);

CREATE TABLE matricula (
    id SERIAL PRIMARY KEY,
    id_alumno INT NOT NULL REFERENCES alumno(id) ON DELETE CASCADE,
    id_modulo INT NOT NULL REFERENCES modulo(id),
    fecha DATE NOT NULL
);
